apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["blakelead.com"]
  resources: ["namespaceresourcesinjectors"]
  verbs: ["list", "get", "watch", "update"]
- apiGroups: ["rbac"]
  resources: ["*"]
  verbs: ["list", "get", "watch", "update"]
